name: mikattack
favicon: null
layout_spectrum: 0.6609057162422687
typography_spectrum: 0.2699963098857552
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.08374535827897489
  lightness: 0.9107126807793975
  saturation: 0.044401480350643396
  rhythmicContrast: 0.5629105637781322
purpose: []
